version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: b42
      MONGO_INITDB_DATABASE: b42
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env.development
    environment:
      MONGODB_HOST: mongodb
    links:
      - mongodb
